In [1]:
import os
import tqdm
import time
import argparse
import torch    

from pit.dataset.mathematical_shapes import MathematicalShapesDataset
from torch.utils.data import DataLoader
from transformers import GPT2LMHeadModel, GPT2Config

[2023-07-24 09:45:20,297] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)


In [2]:
num_shapes=102
train_dataset = MathematicalShapesDataset( # sum to not 100
                                      train=True,
                                      rule_indices=[0,4], 
                                      num_shapes=num_shapes,
                                      num_samples=1000000, 
                                      return_rule_label=True)

In [3]:
device='cuda:0'
config=GPT2Config(n_layer=2, vocab_size=train_dataset.vocab_len, eos_token_id=train_dataset.eos_token)
model = GPT2LMHeadModel(config=config).to(device)

In [14]:
dic = model.state_dict()
print(dic.keys())
# dv = model.device
# dv

# cv = torch.tensor([0, 1], device = dv)
# cv.device

odict_keys(['transformer.wte.weight', 'transformer.wpe.weight', 'transformer.h.0.ln_1.weight', 'transformer.h.0.ln_1.bias', 'transformer.h.0.attn.c_attn.weight', 'transformer.h.0.attn.c_attn.bias', 'transformer.h.0.attn.c_proj.weight', 'transformer.h.0.attn.c_proj.bias', 'transformer.h.0.ln_2.weight', 'transformer.h.0.ln_2.bias', 'transformer.h.0.mlp.c_fc.weight', 'transformer.h.0.mlp.c_fc.bias', 'transformer.h.0.mlp.c_proj.weight', 'transformer.h.0.mlp.c_proj.bias', 'transformer.h.1.ln_1.weight', 'transformer.h.1.ln_1.bias', 'transformer.h.1.attn.c_attn.weight', 'transformer.h.1.attn.c_attn.bias', 'transformer.h.1.attn.c_proj.weight', 'transformer.h.1.attn.c_proj.bias', 'transformer.h.1.ln_2.weight', 'transformer.h.1.ln_2.bias', 'transformer.h.1.mlp.c_fc.weight', 'transformer.h.1.mlp.c_fc.bias', 'transformer.h.1.mlp.c_proj.weight', 'transformer.h.1.mlp.c_proj.bias', 'transformer.ln_f.weight', 'transformer.ln_f.bias', 'lm_head.weight'])


In [18]:
from datetime import datetime

# datetime.today()            # 현재 날짜 가져오기

# datetime.today().year        # 현재 연도 가져오기

# datetime.today().month      # 현재 월 가져오기

# datetime.today().day

print(f'{datetime.today().month}_{datetime.today().day}')

7_24


In [19]:
num_shapes=102
train_dataset = MathematicalShapesDataset( # sum to not 100
                                    train=True,
                                    rule_indices=[0,4], 
                                    num_shapes=num_shapes,
                                    num_samples=1000000, 
                                    return_rule_label=True)

In [20]:
loader = DataLoader(train_dataset, batch_size=1)
for i in loader:
    i['input_ids'] = i['input_ids'].to(device)
    i['labels'] = i['input_ids'].to(device)
    output = model(**i)
    break

In [26]:
train_dataset[0]

{'input_ids': tensor([109,  45, 104,  48, 102,  93, 109, 109])}

In [36]:
for i in range(10):
    if not(i % 5) or (i==9):
        print(i)

0
5
9


In [5]:
train_dataset[1579]

{'input_ids': tensor([109,  56, 104,  45, 102, 101, 109, 109])}

In [6]:
train_dataset.vocab_len

110

For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

In [7]:
import numpy as np


In [10]:
np.random.randint(100)

2

In [11]:
train_dataset[0]

{'input_ids': tensor([109,   1, 104,   0, 102,   1, 109, 109])}

In [26]:
sam = train_dataset[0]['input_ids'].to(device)
sa = model.generate(sam[:5].unsqueeze(0), max_new_tokens=3, min_new_tokens=3)
print(sam)
print(sa)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:109 for open-end generation.


tensor([109,   1, 104,   0, 102,   1, 109, 109], device='cuda:0')
tensor([[109,   1, 104,   0, 102,  49,  49,  49]], device='cuda:0')


In [25]:
sam

tensor([109,   1, 104,   0, 102,   1, 109, 109], device='cuda:0')